version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    # Group all updates together
    groups:
      all-updates:
        patterns:
          - "*"
    # Specify rules for version updates
    open-pull-requests-limit: 10
    # Assign reviewers (optional)
    reviewers:
      - "autoparallel"
    # Labels for PRs (optional)
    labels:
      - "dependencies"
      - "automated pr"
    # Configure commit message
    commit-message:
      prefix: "chore"
      include: "scope"
    # Only allow certain update types (optional)
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"