repository:
  # Enable all features
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false

  # Default branch (recommended to use "main")
  default_branch: main

  # Enable vulnerability alerts
  enable_vulnerability_alerts: true

  # Allow squash merging only
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true

  # Use PR title as squash commit message
  squash_merge_commit_title: PR_TITLE
  squash_merge_commit_message: BLANK

  # Delete head branch after merge
  delete_branch_on_merge: true

# Branch protection rules
branches:
  - name: main
    protection:
      # Require pull request before merging
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false

      # Require status checks to pass
      required_status_checks:
        strict: true
        contexts: []  # Add your required status checks here

      # Prevent direct pushes to main
      enforce_admins: true

      # Restrict who can push to matching branches
      restrictions: null  # Set to null to allow any user with push access
