[package]
authors     = ["Colin Roberts"]
description = "A Rust implementation of Customizable Constraint Systems (CCS)."
edition     = "2021"
keywords    = ["cryptography", "zk"]
license     = "MIT"
name        = "custom-constraints"
readme      = "README.md"
repository  = "https://github.com/autoparallel/custom-constraints"
version     = "0.2.0"

# Needed to deal with ark-ff's BS
[features]
asm     = []
default = []

[dependencies]
# Should be behind a feat so we can still publish (or use crates version of ACVM?)
acvm       = { git = "https://github.com/noir-lang/noir" }
serde      = { version = "1.0" }
serde_json = { version = "1.0" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
ark-ff = { version = "0.5", features = ["parallel", "asm"] }

[target.'cfg(not(target_arch = "x86_64"))'.dependencies]
ark-ff = { version = "0.5", default-features = false, features = ["parallel"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
# Need `getrandom` 0.2 to overwrite the features since other crates use this now.
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
ark-bn254 = { version = "0.5" }
ark-std   = { version = "0.5", default-features = false, features = ["std"] }
# Need `rand` 0.8 to overwrite the features since other crates use this now.
rand   = { version = "0.8" }
rstest = { version = "0.24", default-features = false }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen      = { version = "0.2" }
wasm-bindgen-test = { version = "0.3" }

[profile.release]
codegen-units = 1
lto           = "fat"
opt-level     = 3
panic         = "abort"
strip         = true
